/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IShadowPool,
  IShadowPoolInterface,
} from "../../../src/ShadowPerps.sol/IShadowPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "trader",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "payTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveTraderLoss",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IShadowPool__factory {
  static readonly abi = _abi;
  static createInterface(): IShadowPoolInterface {
    return new Interface(_abi) as IShadowPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IShadowPool {
    return new Contract(address, _abi, runner) as unknown as IShadowPool;
  }
}
