/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface IConfidentialAssetVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "controllerTransfer"
      | "depositPublic"
      | "finalizePublicWithdraw"
      | "getBalanceCiphertext"
      | "getWithdrawRequestCiphertexts"
      | "getWithdrawRequestMeta"
      | "requestPublicWithdraw"
      | "setController"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "controllerTransfer",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPublic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePublicWithdraw",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalanceCiphertext",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestPublicWithdraw",
    values: [InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "controllerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePublicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalanceCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPublicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
}

export interface IConfidentialAssetVault extends BaseContract {
  connect(runner?: ContractRunner | null): IConfidentialAssetVault;
  waitForDeployment(): Promise<this>;

  interface: IConfidentialAssetVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  controllerTransfer: TypedContractMethod<
    [amountCtHash: BytesLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  depositPublic: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizePublicWithdraw: TypedContractMethod<
    [
      requestId: BigNumberish,
      amount: BigNumberish,
      canWithdraw: boolean,
      amountSignature: BytesLike,
      canWithdrawSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getBalanceCiphertext: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getWithdrawRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { amountCtHash: string; canWithdrawCtHash: string }],
    "view"
  >;

  getWithdrawRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  requestPublicWithdraw: TypedContractMethod<
    [amountInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  setController: TypedContractMethod<
    [controller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "controllerTransfer"
  ): TypedContractMethod<
    [amountCtHash: BytesLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositPublic"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizePublicWithdraw"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      amount: BigNumberish,
      canWithdraw: boolean,
      amountSignature: BytesLike,
      canWithdrawSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalanceCiphertext"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWithdrawRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { amountCtHash: string; canWithdrawCtHash: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestPublicWithdraw"
  ): TypedContractMethod<
    [amountInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<
    [controller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
