/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface IShadowPoolV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "finalizeDeposit"
      | "finalizeWithdraw"
      | "getDepositRequestCiphertexts"
      | "getDepositRequestMeta"
      | "getPoolCiphertexts"
      | "getProviderCiphertexts"
      | "getWithdrawRequestCiphertexts"
      | "getWithdrawRequestMeta"
      | "requestDeposit"
      | "requestWithdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "finalizeDeposit",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdraw",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCiphertexts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderCiphertexts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeposit",
    values: [InEuint128Struct, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [InEuint128Struct, InEuint128Struct]
  ): string;

  decodeFunctionResult(
    functionFragment: "finalizeDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
}

export interface IShadowPoolV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IShadowPoolV2;
  waitForDeployment(): Promise<this>;

  interface: IShadowPoolV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  finalizeDeposit: TypedContractMethod<
    [
      requestId: BigNumberish,
      sharesOut: BigNumberish,
      canFinalize: boolean,
      sharesOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  finalizeWithdraw: TypedContractMethod<
    [
      requestId: BigNumberish,
      assetsOut: BigNumberish,
      canFinalize: boolean,
      assetsOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDepositRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        assetAmountCtHash: string;
        minSharesOutCtHash: string;
        quotedSharesOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;

  getDepositRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getPoolCiphertexts: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        totalSharesCtHash: string;
        totalAssetsCtHash: string;
        cumulativeFeesCtHash: string;
        cumulativeTraderPnlCtHash: string;
      }
    ],
    "view"
  >;

  getProviderCiphertexts: TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, string] & {
        shareBalanceCtHash: string;
        principalCtHash: string;
        pendingWithdrawCtHash: string;
      }
    ],
    "view"
  >;

  getWithdrawRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        shareAmountCtHash: string;
        minAssetsOutCtHash: string;
        quotedAssetsOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;

  getWithdrawRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  requestDeposit: TypedContractMethod<
    [assetAmountInput: InEuint128Struct, minSharesOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  requestWithdraw: TypedContractMethod<
    [shareAmountInput: InEuint128Struct, minAssetsOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "finalizeDeposit"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      sharesOut: BigNumberish,
      canFinalize: boolean,
      sharesOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdraw"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      assetsOut: BigNumberish,
      canFinalize: boolean,
      assetsOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDepositRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        assetAmountCtHash: string;
        minSharesOutCtHash: string;
        quotedSharesOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDepositRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCiphertexts"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        totalSharesCtHash: string;
        totalAssetsCtHash: string;
        cumulativeFeesCtHash: string;
        cumulativeTraderPnlCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderCiphertexts"
  ): TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, string] & {
        shareBalanceCtHash: string;
        principalCtHash: string;
        pendingWithdrawCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        shareAmountCtHash: string;
        minAssetsOutCtHash: string;
        quotedAssetsOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestDeposit"
  ): TypedContractMethod<
    [assetAmountInput: InEuint128Struct, minSharesOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<
    [shareAmountInput: InEuint128Struct, minAssetsOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
