/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IShadowPoolSettlementV2Interface extends Interface {
  getFunction(
    nameOrSignature: "recordTraderDelta" | "recordTradingFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "recordTraderDelta",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTradingFee",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordTraderDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTradingFee",
    data: BytesLike
  ): Result;
}

export interface IShadowPoolSettlementV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IShadowPoolSettlementV2;
  waitForDeployment(): Promise<this>;

  interface: IShadowPoolSettlementV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordTraderDelta: TypedContractMethod<
    [deltaCtHash: BytesLike, traderWins: boolean],
    [void],
    "nonpayable"
  >;

  recordTradingFee: TypedContractMethod<
    [feeCtHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordTraderDelta"
  ): TypedContractMethod<
    [deltaCtHash: BytesLike, traderWins: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTradingFee"
  ): TypedContractMethod<[feeCtHash: BytesLike], [void], "nonpayable">;

  filters: {};
}
