/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialAssetVault,
  IConfidentialAssetVaultInterface,
} from "../../../src/interfaces/IConfidentialAssetVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "amountCtHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "controllerTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositPublic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
      {
        internalType: "bool",
        name: "canWithdraw",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "amountSignature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "canWithdrawSignature",
        type: "bytes",
      },
    ],
    name: "finalizePublicWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getBalanceCiphertext",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getWithdrawRequestCiphertexts",
    outputs: [
      {
        internalType: "bytes32",
        name: "amountCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "canWithdrawCtHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getWithdrawRequestMeta",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
      {
        internalType: "enum IConfidentialAssetVault.WithdrawRequestStatus",
        name: "status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "ctHash",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "securityZone",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "utype",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct InEuint128",
        name: "amountInput",
        type: "tuple",
      },
    ],
    name: "requestPublicWithdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
    ],
    name: "setController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConfidentialAssetVault__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialAssetVaultInterface {
    return new Interface(_abi) as IConfidentialAssetVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialAssetVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfidentialAssetVault;
  }
}
