/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IShadowPoolSettlementV2,
  IShadowPoolSettlementV2Interface,
} from "../../../src/interfaces/IShadowPoolSettlementV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "deltaCtHash",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "traderWins",
        type: "bool",
      },
    ],
    name: "recordTraderDelta",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feeCtHash",
        type: "bytes32",
      },
    ],
    name: "recordTradingFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IShadowPoolSettlementV2__factory {
  static readonly abi = _abi;
  static createInterface(): IShadowPoolSettlementV2Interface {
    return new Interface(_abi) as IShadowPoolSettlementV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IShadowPoolSettlementV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IShadowPoolSettlementV2;
  }
}
