/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IShadowPoolV2,
  IShadowPoolV2Interface,
} from "../../../src/interfaces/IShadowPoolV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "sharesOut",
        type: "uint128",
      },
      {
        internalType: "bool",
        name: "canFinalize",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "sharesOutSignature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "canFinalizeSignature",
        type: "bytes",
      },
    ],
    name: "finalizeDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "assetsOut",
        type: "uint128",
      },
      {
        internalType: "bool",
        name: "canFinalize",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "assetsOutSignature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "canFinalizeSignature",
        type: "bytes",
      },
    ],
    name: "finalizeWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getDepositRequestCiphertexts",
    outputs: [
      {
        internalType: "bytes32",
        name: "assetAmountCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "minSharesOutCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "quotedSharesOutCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "canFinalizeCtHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getDepositRequestMeta",
    outputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
      {
        internalType: "enum IShadowPoolV2.RequestStatus",
        name: "status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolCiphertexts",
    outputs: [
      {
        internalType: "bytes32",
        name: "totalSharesCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "totalAssetsCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "cumulativeFeesCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "cumulativeTraderPnlCtHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "getProviderCiphertexts",
    outputs: [
      {
        internalType: "bytes32",
        name: "shareBalanceCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "principalCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "pendingWithdrawCtHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getWithdrawRequestCiphertexts",
    outputs: [
      {
        internalType: "bytes32",
        name: "shareAmountCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "minAssetsOutCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "quotedAssetsOutCtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "canFinalizeCtHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getWithdrawRequestMeta",
    outputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
      {
        internalType: "enum IShadowPoolV2.RequestStatus",
        name: "status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "ctHash",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "securityZone",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "utype",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct InEuint128",
        name: "assetAmountInput",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "ctHash",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "securityZone",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "utype",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct InEuint128",
        name: "minSharesOutInput",
        type: "tuple",
      },
    ],
    name: "requestDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "ctHash",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "securityZone",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "utype",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct InEuint128",
        name: "shareAmountInput",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "ctHash",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "securityZone",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "utype",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct InEuint128",
        name: "minAssetsOutInput",
        type: "tuple",
      },
    ],
    name: "requestWithdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IShadowPoolV2__factory {
  static readonly abi = _abi;
  static createInterface(): IShadowPoolV2Interface {
    return new Interface(_abi) as IShadowPoolV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IShadowPoolV2 {
    return new Contract(address, _abi, runner) as unknown as IShadowPoolV2;
  }
}
