/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracle } from "./IPriceOracle";
export type { IShadowPool } from "./IShadowPool";
export type { ShadowPerps } from "./ShadowPerps";
