/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type InEboolStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEboolStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface ShadowPerpsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "addMarket"
      | "finalizeClosePosition"
      | "finalizeLiquidation"
      | "finalizeOpenPosition"
      | "getOpenRequestMeta"
      | "getOpenRequestValidationCiphertext"
      | "getPositionCiphertexts"
      | "getPositionMeta"
      | "getTraderPositionCount"
      | "getTraderPositionIds"
      | "marketSymbols"
      | "maxLeverage"
      | "openRequestCount"
      | "oracle"
      | "owner"
      | "pool"
      | "positionCount"
      | "renounceOwnership"
      | "requestClosePosition"
      | "requestLiquidationCheck"
      | "requestOpenPosition"
      | "setOracle"
      | "setPool"
      | "supportedMarkets"
      | "totalCollateral"
      | "traderPositions"
      | "tradingFeeRate"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CloseRequested"
      | "LiquidationCheckRequested"
      | "MarketAdded"
      | "OpenValidationRequested"
      | "OwnershipTransferred"
      | "PositionClosed"
      | "PositionLiquidated"
      | "PositionOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addMarket", values: [string]): string;
  encodeFunctionData(
    functionFragment: "finalizeClosePosition",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeLiquidation",
    values: [BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeOpenPosition",
    values: [BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenRequestValidationCiphertext",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderPositionIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketSymbols",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxLeverage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestClosePosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLiquidationCheck",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestOpenPosition",
    values: [string, BigNumberish, InEboolStruct, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedMarkets",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "traderPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradingFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeClosePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenRequestValidationCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderPositionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketSymbols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestClosePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLiquidationCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "traderPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace CloseRequestedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    payoutCtHash: BytesLike,
    exitPrice: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    payoutCtHash: string,
    exitPrice: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    payoutCtHash: string;
    exitPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationCheckRequestedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    canLiquidateCtHash: BytesLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    canLiquidateCtHash: string,
    price: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    canLiquidateCtHash: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAddedEvent {
  export type InputTuple = [marketId: BytesLike, symbol: string];
  export type OutputTuple = [marketId: string, symbol: string];
  export interface OutputObject {
    marketId: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpenValidationRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    trader: AddressLike,
    marketId: BytesLike,
    validationCtHash: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    trader: string,
    marketId: string,
    validationCtHash: string
  ];
  export interface OutputObject {
    requestId: bigint;
    trader: string;
    marketId: string;
    validationCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    trader: AddressLike,
    payout: BigNumberish,
    pnl: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    trader: string,
    payout: bigint,
    pnl: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    trader: string;
    payout: bigint;
    pnl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLiquidatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    trader: AddressLike,
    collateralLost: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    trader: string,
    collateralLost: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    trader: string;
    collateralLost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    trader: AddressLike,
    marketId: BytesLike,
    collateral: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    trader: string,
    marketId: string,
    collateral: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    trader: string;
    marketId: string;
    collateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShadowPerps extends BaseContract {
  connect(runner?: ContractRunner | null): ShadowPerps;
  waitForDeployment(): Promise<this>;

  interface: ShadowPerpsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  addMarket: TypedContractMethod<[symbol: string], [void], "nonpayable">;

  finalizeClosePosition: TypedContractMethod<
    [positionId: BigNumberish, payout: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeLiquidation: TypedContractMethod<
    [positionId: BigNumberish, liquidatable: boolean, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeOpenPosition: TypedContractMethod<
    [requestId: BigNumberish, canOpen: boolean, signature: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getOpenRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint] & {
        trader: string;
        marketId: string;
        collateral: bigint;
      }
    ],
    "view"
  >;

  getOpenRequestValidationCiphertext: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "view"
  >;

  getPositionCiphertexts: TypedContractMethod<
    [positionId: BigNumberish],
    [
      [string, string, string, string] & {
        directionCtHash: string;
        sizeCtHash: string;
        closePayoutCtHash: string;
        liquidationCheckCtHash: string;
      }
    ],
    "view"
  >;

  getPositionMeta: TypedContractMethod<
    [positionId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        trader: string;
        marketId: string;
        collateral: bigint;
        entryPrice: bigint;
        openedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getTraderPositionCount: TypedContractMethod<
    [trader: AddressLike],
    [bigint],
    "view"
  >;

  getTraderPositionIds: TypedContractMethod<
    [trader: AddressLike],
    [bigint[]],
    "view"
  >;

  marketSymbols: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  maxLeverage: TypedContractMethod<[], [bigint], "view">;

  openRequestCount: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  positionCount: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestClosePosition: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestLiquidationCheck: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestOpenPosition: TypedContractMethod<
    [
      symbol: string,
      collateralUsdc: BigNumberish,
      directionInput: InEboolStruct,
      sizeInput: InEuint128Struct
    ],
    [bigint],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;

  setPool: TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;

  supportedMarkets: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  totalCollateral: TypedContractMethod<[], [bigint], "view">;

  traderPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  tradingFeeRate: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addMarket"
  ): TypedContractMethod<[symbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeClosePosition"
  ): TypedContractMethod<
    [positionId: BigNumberish, payout: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeLiquidation"
  ): TypedContractMethod<
    [positionId: BigNumberish, liquidatable: boolean, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeOpenPosition"
  ): TypedContractMethod<
    [requestId: BigNumberish, canOpen: boolean, signature: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOpenRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint] & {
        trader: string;
        marketId: string;
        collateral: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpenRequestValidationCiphertext"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPositionCiphertexts"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [
      [string, string, string, string] & {
        directionCtHash: string;
        sizeCtHash: string;
        closePayoutCtHash: string;
        liquidationCheckCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionMeta"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        trader: string;
        marketId: string;
        collateral: bigint;
        entryPrice: bigint;
        openedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTraderPositionCount"
  ): TypedContractMethod<[trader: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTraderPositionIds"
  ): TypedContractMethod<[trader: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "marketSymbols"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "maxLeverage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestClosePosition"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLiquidationCheck"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestOpenPosition"
  ): TypedContractMethod<
    [
      symbol: string,
      collateralUsdc: BigNumberish,
      directionInput: InEboolStruct,
      sizeInput: InEuint128Struct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPool"
  ): TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedMarkets"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalCollateral"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "traderPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tradingFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CloseRequested"
  ): TypedContractEvent<
    CloseRequestedEvent.InputTuple,
    CloseRequestedEvent.OutputTuple,
    CloseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationCheckRequested"
  ): TypedContractEvent<
    LiquidationCheckRequestedEvent.InputTuple,
    LiquidationCheckRequestedEvent.OutputTuple,
    LiquidationCheckRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MarketAdded"
  ): TypedContractEvent<
    MarketAddedEvent.InputTuple,
    MarketAddedEvent.OutputTuple,
    MarketAddedEvent.OutputObject
  >;
  getEvent(
    key: "OpenValidationRequested"
  ): TypedContractEvent<
    OpenValidationRequestedEvent.InputTuple,
    OpenValidationRequestedEvent.OutputTuple,
    OpenValidationRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLiquidated"
  ): TypedContractEvent<
    PositionLiquidatedEvent.InputTuple,
    PositionLiquidatedEvent.OutputTuple,
    PositionLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;

  filters: {
    "CloseRequested(uint256,bytes32,uint256)": TypedContractEvent<
      CloseRequestedEvent.InputTuple,
      CloseRequestedEvent.OutputTuple,
      CloseRequestedEvent.OutputObject
    >;
    CloseRequested: TypedContractEvent<
      CloseRequestedEvent.InputTuple,
      CloseRequestedEvent.OutputTuple,
      CloseRequestedEvent.OutputObject
    >;

    "LiquidationCheckRequested(uint256,bytes32,uint256)": TypedContractEvent<
      LiquidationCheckRequestedEvent.InputTuple,
      LiquidationCheckRequestedEvent.OutputTuple,
      LiquidationCheckRequestedEvent.OutputObject
    >;
    LiquidationCheckRequested: TypedContractEvent<
      LiquidationCheckRequestedEvent.InputTuple,
      LiquidationCheckRequestedEvent.OutputTuple,
      LiquidationCheckRequestedEvent.OutputObject
    >;

    "MarketAdded(bytes32,string)": TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;
    MarketAdded: TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;

    "OpenValidationRequested(uint256,address,bytes32,bytes32)": TypedContractEvent<
      OpenValidationRequestedEvent.InputTuple,
      OpenValidationRequestedEvent.OutputTuple,
      OpenValidationRequestedEvent.OutputObject
    >;
    OpenValidationRequested: TypedContractEvent<
      OpenValidationRequestedEvent.InputTuple,
      OpenValidationRequestedEvent.OutputTuple,
      OpenValidationRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionClosed(uint256,address,uint256,int256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionLiquidated(uint256,address,uint256)": TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;
    PositionLiquidated: TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;

    "PositionOpened(uint256,address,bytes32,uint256)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
  };
}
