/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface ConfidentialAssetVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "controllerTransfer"
      | "controllers"
      | "depositPublic"
      | "finalizePublicWithdraw"
      | "getBalanceCiphertext"
      | "getWithdrawRequestCiphertexts"
      | "getWithdrawRequestMeta"
      | "owner"
      | "renounceOwnership"
      | "requestPublicWithdraw"
      | "setController"
      | "transferOwnership"
      | "withdrawRequestCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ControllerTransferApplied"
      | "ControllerUpdated"
      | "OwnershipTransferred"
      | "PublicDeposit"
      | "PublicWithdrawFinalized"
      | "PublicWithdrawRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "controllerTransfer",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPublic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePublicWithdraw",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalanceCiphertext",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestPublicWithdraw",
    values: [InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRequestCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePublicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalanceCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPublicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRequestCount",
    data: BytesLike
  ): Result;
}

export namespace ControllerTransferAppliedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amountCtHash: BytesLike
  ];
  export type OutputTuple = [from: string, to: string, amountCtHash: string];
  export interface OutputObject {
    from: string;
    to: string;
    amountCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ControllerUpdatedEvent {
  export type InputTuple = [controller: AddressLike, allowed: boolean];
  export type OutputTuple = [controller: string, allowed: boolean];
  export interface OutputObject {
    controller: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDepositEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicWithdrawFinalizedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    account: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    account: string,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicWithdrawRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    account: AddressLike,
    amountCtHash: BytesLike,
    canWithdrawCtHash: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    account: string,
    amountCtHash: string,
    canWithdrawCtHash: string
  ];
  export interface OutputObject {
    requestId: bigint;
    account: string;
    amountCtHash: string;
    canWithdrawCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialAssetVault extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialAssetVault;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialAssetVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  controllerTransfer: TypedContractMethod<
    [amountCtHash: BytesLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  controllers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  depositPublic: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizePublicWithdraw: TypedContractMethod<
    [
      requestId: BigNumberish,
      amount: BigNumberish,
      canWithdraw: boolean,
      amountSignature: BytesLike,
      canWithdrawSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getBalanceCiphertext: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getWithdrawRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { amountCtHash: string; canWithdrawCtHash: string }],
    "view"
  >;

  getWithdrawRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestPublicWithdraw: TypedContractMethod<
    [amountInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  setController: TypedContractMethod<
    [controller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawRequestCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "controllerTransfer"
  ): TypedContractMethod<
    [amountCtHash: BytesLike, from: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "controllers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "depositPublic"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizePublicWithdraw"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      amount: BigNumberish,
      canWithdraw: boolean,
      amountSignature: BytesLike,
      canWithdrawSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalanceCiphertext"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWithdrawRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { amountCtHash: string; canWithdrawCtHash: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestPublicWithdraw"
  ): TypedContractMethod<
    [amountInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<
    [controller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ControllerTransferApplied"
  ): TypedContractEvent<
    ControllerTransferAppliedEvent.InputTuple,
    ControllerTransferAppliedEvent.OutputTuple,
    ControllerTransferAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ControllerUpdated"
  ): TypedContractEvent<
    ControllerUpdatedEvent.InputTuple,
    ControllerUpdatedEvent.OutputTuple,
    ControllerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PublicDeposit"
  ): TypedContractEvent<
    PublicDepositEvent.InputTuple,
    PublicDepositEvent.OutputTuple,
    PublicDepositEvent.OutputObject
  >;
  getEvent(
    key: "PublicWithdrawFinalized"
  ): TypedContractEvent<
    PublicWithdrawFinalizedEvent.InputTuple,
    PublicWithdrawFinalizedEvent.OutputTuple,
    PublicWithdrawFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PublicWithdrawRequested"
  ): TypedContractEvent<
    PublicWithdrawRequestedEvent.InputTuple,
    PublicWithdrawRequestedEvent.OutputTuple,
    PublicWithdrawRequestedEvent.OutputObject
  >;

  filters: {
    "ControllerTransferApplied(address,address,bytes32)": TypedContractEvent<
      ControllerTransferAppliedEvent.InputTuple,
      ControllerTransferAppliedEvent.OutputTuple,
      ControllerTransferAppliedEvent.OutputObject
    >;
    ControllerTransferApplied: TypedContractEvent<
      ControllerTransferAppliedEvent.InputTuple,
      ControllerTransferAppliedEvent.OutputTuple,
      ControllerTransferAppliedEvent.OutputObject
    >;

    "ControllerUpdated(address,bool)": TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;
    ControllerUpdated: TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PublicDeposit(address,uint256)": TypedContractEvent<
      PublicDepositEvent.InputTuple,
      PublicDepositEvent.OutputTuple,
      PublicDepositEvent.OutputObject
    >;
    PublicDeposit: TypedContractEvent<
      PublicDepositEvent.InputTuple,
      PublicDepositEvent.OutputTuple,
      PublicDepositEvent.OutputObject
    >;

    "PublicWithdrawFinalized(uint256,address,uint256)": TypedContractEvent<
      PublicWithdrawFinalizedEvent.InputTuple,
      PublicWithdrawFinalizedEvent.OutputTuple,
      PublicWithdrawFinalizedEvent.OutputObject
    >;
    PublicWithdrawFinalized: TypedContractEvent<
      PublicWithdrawFinalizedEvent.InputTuple,
      PublicWithdrawFinalizedEvent.OutputTuple,
      PublicWithdrawFinalizedEvent.OutputObject
    >;

    "PublicWithdrawRequested(uint256,address,bytes32,bytes32)": TypedContractEvent<
      PublicWithdrawRequestedEvent.InputTuple,
      PublicWithdrawRequestedEvent.OutputTuple,
      PublicWithdrawRequestedEvent.OutputObject
    >;
    PublicWithdrawRequested: TypedContractEvent<
      PublicWithdrawRequestedEvent.InputTuple,
      PublicWithdrawRequestedEvent.OutputTuple,
      PublicWithdrawRequestedEvent.OutputObject
    >;
  };
}
