/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHETestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lastEncrypted"
      | "lastSuccess"
      | "testAdd"
      | "testTrivialEncrypt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lastEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastSuccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testAdd",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testTrivialEncrypt",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "lastEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testAdd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testTrivialEncrypt",
    data: BytesLike
  ): Result;
}

export interface FHETest extends BaseContract {
  connect(runner?: ContractRunner | null): FHETest;
  waitForDeployment(): Promise<this>;

  interface: FHETestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lastEncrypted: TypedContractMethod<[], [string], "view">;

  lastSuccess: TypedContractMethod<[], [boolean], "view">;

  testAdd: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [void],
    "nonpayable"
  >;

  testTrivialEncrypt: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lastEncrypted"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastSuccess"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "testAdd"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "testTrivialEncrypt"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  filters: {};
}
