/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface ShadowPoolV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetVault"
      | "depositRequestCount"
      | "finalizeDeposit"
      | "finalizeWithdraw"
      | "getDepositRequestCiphertexts"
      | "getDepositRequestMeta"
      | "getPoolCiphertexts"
      | "getProviderCiphertexts"
      | "getWithdrawRequestCiphertexts"
      | "getWithdrawRequestMeta"
      | "owner"
      | "perpsContract"
      | "recordTraderDelta"
      | "recordTradingFee"
      | "renounceOwnership"
      | "requestDeposit"
      | "requestWithdraw"
      | "setAssetVault"
      | "setPerpsContract"
      | "transferOwnership"
      | "withdrawRequestCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetVaultUpdated"
      | "DepositFinalized"
      | "DepositRequested"
      | "OwnershipTransferred"
      | "PerpsContractUpdated"
      | "TraderDeltaRecorded"
      | "TradingFeeRecorded"
      | "WithdrawFinalized"
      | "WithdrawRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDeposit",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdraw",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCiphertexts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderCiphertexts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestCiphertexts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawRequestMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "perpsContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordTraderDelta",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTradingFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeposit",
    values: [InEuint128Struct, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [InEuint128Struct, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPerpsContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRequestCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "assetVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestCiphertexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawRequestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perpsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTraderDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTradingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPerpsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRequestCount",
    data: BytesLike
  ): Result;
}

export namespace AssetVaultUpdatedEvent {
  export type InputTuple = [assetVault: AddressLike];
  export type OutputTuple = [assetVault: string];
  export interface OutputObject {
    assetVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositFinalizedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    provider: AddressLike,
    sharesOut: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    provider: string,
    sharesOut: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    provider: string;
    sharesOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    provider: AddressLike,
    quotedSharesOutCtHash: BytesLike,
    canFinalizeCtHash: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    provider: string,
    quotedSharesOutCtHash: string,
    canFinalizeCtHash: string
  ];
  export interface OutputObject {
    requestId: bigint;
    provider: string;
    quotedSharesOutCtHash: string;
    canFinalizeCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerpsContractUpdatedEvent {
  export type InputTuple = [perpsContract: AddressLike];
  export type OutputTuple = [perpsContract: string];
  export interface OutputObject {
    perpsContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TraderDeltaRecordedEvent {
  export type InputTuple = [deltaCtHash: BytesLike, traderWins: boolean];
  export type OutputTuple = [deltaCtHash: string, traderWins: boolean];
  export interface OutputObject {
    deltaCtHash: string;
    traderWins: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingFeeRecordedEvent {
  export type InputTuple = [feeCtHash: BytesLike];
  export type OutputTuple = [feeCtHash: string];
  export interface OutputObject {
    feeCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawFinalizedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    provider: AddressLike,
    assetsOut: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    provider: string,
    assetsOut: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    provider: string;
    assetsOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    provider: AddressLike,
    quotedAssetsOutCtHash: BytesLike,
    canFinalizeCtHash: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    provider: string,
    quotedAssetsOutCtHash: string,
    canFinalizeCtHash: string
  ];
  export interface OutputObject {
    requestId: bigint;
    provider: string;
    quotedAssetsOutCtHash: string;
    canFinalizeCtHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShadowPoolV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ShadowPoolV2;
  waitForDeployment(): Promise<this>;

  interface: ShadowPoolV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetVault: TypedContractMethod<[], [string], "view">;

  depositRequestCount: TypedContractMethod<[], [bigint], "view">;

  finalizeDeposit: TypedContractMethod<
    [
      requestId: BigNumberish,
      sharesOut: BigNumberish,
      canFinalize: boolean,
      sharesOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  finalizeWithdraw: TypedContractMethod<
    [
      requestId: BigNumberish,
      assetsOut: BigNumberish,
      canFinalize: boolean,
      assetsOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDepositRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        assetAmountCtHash: string;
        minSharesOutCtHash: string;
        quotedSharesOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;

  getDepositRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getPoolCiphertexts: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        totalSharesCtHash: string;
        totalAssetsCtHash: string;
        cumulativeFeesCtHash: string;
        cumulativeTraderPnlCtHash: string;
      }
    ],
    "view"
  >;

  getProviderCiphertexts: TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, string] & {
        shareBalanceCtHash: string;
        principalCtHash: string;
        pendingWithdrawCtHash: string;
      }
    ],
    "view"
  >;

  getWithdrawRequestCiphertexts: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        shareAmountCtHash: string;
        minAssetsOutCtHash: string;
        quotedAssetsOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;

  getWithdrawRequestMeta: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  perpsContract: TypedContractMethod<[], [string], "view">;

  recordTraderDelta: TypedContractMethod<
    [deltaCtHash: BytesLike, traderWins: boolean],
    [void],
    "nonpayable"
  >;

  recordTradingFee: TypedContractMethod<
    [feeCtHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestDeposit: TypedContractMethod<
    [assetAmountInput: InEuint128Struct, minSharesOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  requestWithdraw: TypedContractMethod<
    [shareAmountInput: InEuint128Struct, minAssetsOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;

  setAssetVault: TypedContractMethod<
    [_assetVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setPerpsContract: TypedContractMethod<
    [_perpsContract: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawRequestCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeDeposit"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      sharesOut: BigNumberish,
      canFinalize: boolean,
      sharesOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdraw"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      assetsOut: BigNumberish,
      canFinalize: boolean,
      assetsOutSignature: BytesLike,
      canFinalizeSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDepositRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        assetAmountCtHash: string;
        minSharesOutCtHash: string;
        quotedSharesOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDepositRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCiphertexts"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        totalSharesCtHash: string;
        totalAssetsCtHash: string;
        cumulativeFeesCtHash: string;
        cumulativeTraderPnlCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderCiphertexts"
  ): TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, string] & {
        shareBalanceCtHash: string;
        principalCtHash: string;
        pendingWithdrawCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestCiphertexts"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, string] & {
        shareAmountCtHash: string;
        minAssetsOutCtHash: string;
        quotedAssetsOutCtHash: string;
        canFinalizeCtHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawRequestMeta"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, bigint, bigint] & {
        provider: string;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "perpsContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordTraderDelta"
  ): TypedContractMethod<
    [deltaCtHash: BytesLike, traderWins: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTradingFee"
  ): TypedContractMethod<[feeCtHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDeposit"
  ): TypedContractMethod<
    [assetAmountInput: InEuint128Struct, minSharesOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<
    [shareAmountInput: InEuint128Struct, minAssetsOutInput: InEuint128Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAssetVault"
  ): TypedContractMethod<[_assetVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPerpsContract"
  ): TypedContractMethod<[_perpsContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AssetVaultUpdated"
  ): TypedContractEvent<
    AssetVaultUpdatedEvent.InputTuple,
    AssetVaultUpdatedEvent.OutputTuple,
    AssetVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositFinalized"
  ): TypedContractEvent<
    DepositFinalizedEvent.InputTuple,
    DepositFinalizedEvent.OutputTuple,
    DepositFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "DepositRequested"
  ): TypedContractEvent<
    DepositRequestedEvent.InputTuple,
    DepositRequestedEvent.OutputTuple,
    DepositRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PerpsContractUpdated"
  ): TypedContractEvent<
    PerpsContractUpdatedEvent.InputTuple,
    PerpsContractUpdatedEvent.OutputTuple,
    PerpsContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TraderDeltaRecorded"
  ): TypedContractEvent<
    TraderDeltaRecordedEvent.InputTuple,
    TraderDeltaRecordedEvent.OutputTuple,
    TraderDeltaRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TradingFeeRecorded"
  ): TypedContractEvent<
    TradingFeeRecordedEvent.InputTuple,
    TradingFeeRecordedEvent.OutputTuple,
    TradingFeeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawFinalized"
  ): TypedContractEvent<
    WithdrawFinalizedEvent.InputTuple,
    WithdrawFinalizedEvent.OutputTuple,
    WithdrawFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawRequested"
  ): TypedContractEvent<
    WithdrawRequestedEvent.InputTuple,
    WithdrawRequestedEvent.OutputTuple,
    WithdrawRequestedEvent.OutputObject
  >;

  filters: {
    "AssetVaultUpdated(address)": TypedContractEvent<
      AssetVaultUpdatedEvent.InputTuple,
      AssetVaultUpdatedEvent.OutputTuple,
      AssetVaultUpdatedEvent.OutputObject
    >;
    AssetVaultUpdated: TypedContractEvent<
      AssetVaultUpdatedEvent.InputTuple,
      AssetVaultUpdatedEvent.OutputTuple,
      AssetVaultUpdatedEvent.OutputObject
    >;

    "DepositFinalized(uint256,address,uint256)": TypedContractEvent<
      DepositFinalizedEvent.InputTuple,
      DepositFinalizedEvent.OutputTuple,
      DepositFinalizedEvent.OutputObject
    >;
    DepositFinalized: TypedContractEvent<
      DepositFinalizedEvent.InputTuple,
      DepositFinalizedEvent.OutputTuple,
      DepositFinalizedEvent.OutputObject
    >;

    "DepositRequested(uint256,address,bytes32,bytes32)": TypedContractEvent<
      DepositRequestedEvent.InputTuple,
      DepositRequestedEvent.OutputTuple,
      DepositRequestedEvent.OutputObject
    >;
    DepositRequested: TypedContractEvent<
      DepositRequestedEvent.InputTuple,
      DepositRequestedEvent.OutputTuple,
      DepositRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PerpsContractUpdated(address)": TypedContractEvent<
      PerpsContractUpdatedEvent.InputTuple,
      PerpsContractUpdatedEvent.OutputTuple,
      PerpsContractUpdatedEvent.OutputObject
    >;
    PerpsContractUpdated: TypedContractEvent<
      PerpsContractUpdatedEvent.InputTuple,
      PerpsContractUpdatedEvent.OutputTuple,
      PerpsContractUpdatedEvent.OutputObject
    >;

    "TraderDeltaRecorded(bytes32,bool)": TypedContractEvent<
      TraderDeltaRecordedEvent.InputTuple,
      TraderDeltaRecordedEvent.OutputTuple,
      TraderDeltaRecordedEvent.OutputObject
    >;
    TraderDeltaRecorded: TypedContractEvent<
      TraderDeltaRecordedEvent.InputTuple,
      TraderDeltaRecordedEvent.OutputTuple,
      TraderDeltaRecordedEvent.OutputObject
    >;

    "TradingFeeRecorded(bytes32)": TypedContractEvent<
      TradingFeeRecordedEvent.InputTuple,
      TradingFeeRecordedEvent.OutputTuple,
      TradingFeeRecordedEvent.OutputObject
    >;
    TradingFeeRecorded: TypedContractEvent<
      TradingFeeRecordedEvent.InputTuple,
      TradingFeeRecordedEvent.OutputTuple,
      TradingFeeRecordedEvent.OutputObject
    >;

    "WithdrawFinalized(uint256,address,uint256)": TypedContractEvent<
      WithdrawFinalizedEvent.InputTuple,
      WithdrawFinalizedEvent.OutputTuple,
      WithdrawFinalizedEvent.OutputObject
    >;
    WithdrawFinalized: TypedContractEvent<
      WithdrawFinalizedEvent.InputTuple,
      WithdrawFinalizedEvent.OutputTuple,
      WithdrawFinalizedEvent.OutputObject
    >;

    "WithdrawRequested(uint256,address,bytes32,bytes32)": TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
    WithdrawRequested: TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
  };
}
